sixdegreesgame/urls.py
from django.urls import path

from . import views

app_name = "sixdegreesgame"
urlpatterns = [
    path("", views.index, name="index"),
    path("help/", views.help, name="help"),
]

sixdegreessite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("sixdegreesgame.urls")),
    path("admin/", admin.site.urls),
]

sixdegreesgame/models.py
from django.db import models

# Create your models here.


class Song(models.Model):
    name = models.CharField(max_length=200)
    artists = ...
    number = ...

    def is_a_valid_answer(self):
        ...

    def is_final_answer(self):
        ...

    def matches_final_artist(self):
        ...

    def __str__(self):
        return f"{self.name}"

sixdegreesgame/views.py
import os
import spotipy
import json
import random
import pprint

from django.shortcuts import render
from django.http import HttpResponse
from spotipy.oauth2 import SpotifyClientCredentials
from dotenv import load_dotenv
from django.http import JsonResponse
from django.template.loader import render_to_string

from .models import Song

load_dotenv()

# Spotify calls

client_id = os.getenv("CLIENT_ID")
client_secret = os.getenv("CLIENT_SECRET")

client_credentials_manager = SpotifyClientCredentials(client_id, client_secret)
spotify = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

# Initialise rappers

def initialise_rappers():
    """
    Grab two random rappers from a list and create a dict for each rapper. Put these dicts in a tuple.
    """
    # List of rappers to choose from
    with open("sixdegreesgame/data/rappers.json", "r") as rappers_file:
        rappers = json.load(rappers_file)

    two_random_rappers = random.sample(rappers, 2)
    return (
        {
            "name": two_random_rappers[0],
            "image": get_rapper_image(two_random_rappers[0]),
        },
        {
            "name": two_random_rappers[1],
            "image": get_rapper_image(two_random_rappers[1]),
        },
    )


# Str -> Dict
def get_rapper_image(str):
    """
    When given an artist name, search the Spotify API and return an image dict for the artist
    """
    rapper_results = spotify.search(q="artist:" + str, type="artist")
    rapper_details = rapper_results["artists"]["items"]
    if len(rapper_details) > 0:
        return rapper_details[0]["images"][0]


# Views

def index(request):
    rappers = initialise_rappers()
    rapper_1 = rappers[0]
    rapper_2 = rappers[1]
    song_1 = Song()
    song_2 = Song()
    
    # Handle the form
    if request.method == "POST":
        if request.POST.get("form-id") == "song-1":
            song_1 = Song(name=request.POST.get("song-name"))
        if request.POST.get("form-id") == "song-2":
            song_2 = Song(name=request.POST.get("song-name"))
        # Delete all songs when user hits "reset"
        if request.POST.get("form-id") == "reset":
            Song.objects.all().delete()
    

    context = {
        "rapper_1": rapper_1,
        "rapper_2": rapper_2,
        "song_1": song_1,
        "song_2": song_2,
    }

    # Check if it's an AJAX request (HTMX request)
    if request.headers.get("HX-Request") == "true":
        # Render the song list template as a string
        song_list_html = render_to_string("sixdegreesgame/includes/song-list.html", context, request)
        pprint.PrettyPrinter(indent=1).pprint(context)

        # Return the updated content as JSON
        return JsonResponse({"html": song_list_html})

    pprint.PrettyPrinter(indent=1).pprint(context)
    return render(request, "sixdegreesgame/index.html", context)


def help(request):
    return render(request, "sixdegreesgame/help.html")

sixdegreesgame/templates/sixdegreesgame/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Six Degrees of the Rap Nation</title>
  <script src="https://unpkg.com/htmx.org@1.9.6" integrity="sha384-FhXw7b6AlE/jyjlZH5iHa/tTe9EpJ1Y55RjcgPbjeWMskSxZt1v9qkxLJWNJaGni" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static '/sixdegreesgame/styles.css' %}">
</head>
<body>
 <header>
  <h1><a href="{% url 'sixdegreesgame:index' %}">Six Degrees of the Rap Nation</a></h1>
  <a href="{% url 'sixdegreesgame:help' %}">?</a>
 </header> 

{% block main %}
{% endblock main %}

 </body>
 </html>

sixdegreesgame/templates/sixdegreesgame/help.html
{% extends "sixdegreesgame/base.html" %}

{% block main %}
  <main>
    <p>This is the help page</p>
  </main>
{% endblock main %}

sixdegreesgame/templates/sixdegreesgame/includes/song-form.html
<div class="song-forms">
  <form
    hx-post="{% url 'sixdegreesgame:index' %}"
    hx-swap=".song-list"
    class="song-form">
    {% csrf_token %}
    <label for="song-1">Song 1</label>
    <input type="hidden" name="form-id" value="song-1">
    <input type="text" name="song-1" value="{{ song_1 }}" id="song-1">
    <input type="submit" value="Submit">
  </form>
  <form action="" class="song-form">
    <label for="">Song 2</label>
    <input type="text" id="song-2">
  </form>
  <form action="" class="song-form">
    <label for="">Song 3</label>
    <input type="text">
  </form>
  <form action="" class="song-form">
    <label for="">Song 4</label>
    <input type="text">
  </form>
  <form action="" class="song-form">
    <label for="">Song 5</label>
    <input type="text">
  </form>
  <form action="" class="song-form">
    <label for="">Song 6</label>
    <input type="text">
  </form>
  <form action="" class="song-form">
    <label for="">Song 7</label>
    <input type="text">
  </form>
  <form action="{% url 'sixdegreesgame:index' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="form-id" value="reset">
    <input type="submit" value="reset">
  </form>
</div>

sixdegreesgame/templates/sixdegreesgame/includes/song-list.html
<ul class="song-list">
  <li>{{ song_1 }}</li>
  <li>{{ song_2 }}</li>
</ul>

sixdegreesgame/templates/sixdegreesgame/index.html
{% extends "sixdegreesgame/base.html" %}

{% block main %}
  <main>
    <ul class="rappers__list">
      <li>
        {{ rapper_1.name }}
        <img src="{{ rapper_1.image.url }}" alt="" class="rappers__image">
      </li>
      <li>
        {{ rapper_2.name }}
        <img src="{{ rapper_2.image.url }}" alt="" class="rappers__image">
      </li>
    </ul>
    <div class="song-forms">
      <form
        hx-post="{% url 'sixdegreesgame:index' %}"
        hx-swap=".song-list"
        hx-target=".song-list"
        class="song-form">
        {% csrf_token %}
        <label for="song-1">Song 1</label>
        <input type="hidden" name="form-id" value="song-1">
        <input type="text" name="song-name" value="{{ song_1 }}" id="song-1">
        <input type="submit" value="Submit">
      </form>
      <form
        hx-post="{% url 'sixdegreesgame:index' %}"
        hx-swap=".song-list"
        hx-target=".song-list"
        class="song-form">
        {% csrf_token %}
        <label for="song-2">Song 1</label>
        <input type="hidden" name="form-id" value="song-2">
        <input type="text" name="song-name" value="{{ song_2 }}" id="song-2">
        <input type="submit" value="Submit">
      </form>
      <form action="" class="song-form">
        <label for="">Song 2</label>
        <input type="text" id="song-2">
      </form>
      <form action="" class="song-form">
        <label for="">Song 3</label>
        <input type="text">
      </form>
      <form action="" class="song-form">
        <label for="">Song 4</label>
        <input type="text">
      </form>
      <form action="" class="song-form">
        <label for="">Song 5</label>
        <input type="text">
      </form>
      <form action="" class="song-form">
        <label for="">Song 6</label>
        <input type="text">
      </form>
      <form action="" class="song-form">
        <label for="">Song 7</label>
        <input type="text">
      </form>
      <form 
        hx-post="{% url 'sixdegreesgame:index' %}"  
        hx-swap=".song-list"
        hx-target=".song-list"
        class="song-form">
        {% csrf_token %}
        <input type="hidden" name="form-id" value="reset">
        <input type="submit" value="reset">
      </form>
    </div>
    {% include "sixdegreesgame/includes/song-list.html" %}
  </main>
{% endblock main %}